spring.data.mongodb.uri=mongodb+srv://pankajdhami007:dhami007@cloudsharecluster.alubyhc.mongodb.net/cloudshare?retryWrites=true&w=majority&appName=CloudShareCluster

server.port=9091
vlogging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

#autho generated password rmov
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://usable-vervet-73.clerk.accounts.dev
clerk.jwks-url=https://usable-vervet-73.clerk.accounts.dev/.well-known/jwks.json
#ADD_YOUR_WEBHOOK_SECRET
clerk.webhook.secret=whsec_FnaX2fYvKA8t4jysuQbvNmgxk93HjJp/

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay configuration
razorpay.key.id=rzp_test_RPOZ7ErSM7NTam
razorpay.key.secret=LgdVxdBRURpUM5IGimJgBHR9