spring.data.mongodb.uri=mongodb+srv://pankajdhami007:dhami007@cloudsharecluster.alubyhc.mongodb.net/cloudshare?retryWrites=true&w=majority&appName=CloudShareCluster
server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://usable-vervet-73.clerk.accounts.dev
clerk.jwks-url=https://usable-vervet-73.clerk.accounts.dev/.well-known/jwks.json
#ADD_YOUR_WEBHOOK_SECRET
clerk.webhook.secret=whsec_pQVQBShJ0VRK4hRnB8R9VIurV+81qOEa

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay configuration
razorpay.key.id=ADD_YOUR_RAZORPAY_KEY
razorpay.key.secret=ADD_YOUR_RAZORPAY_SECRET